# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Rev Indy
email: revindy@iuhealth.org
description: Kick off the greatest month in racing with Methodist Health Foundation’s Rev at the Indianapolis Motor Speedway.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#981E32'
author: TrendyMinds.com
logo: assets/images/large-logo.png

include: ['_pages', '.htaccess']

keep_files: [images]

permalink: /:title/

## Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
google_analytics: UA-58727926-1

### Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - octopress-minify-html

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - node_modules
